defaults:
  - _self_
  - drone
  - ppo
  - sim
  - user_model

headless: True
profiling_mode: False
eval_visualization: True
log_output_dir: "./outputs"
device: "cuda:0"
seed: 0

# Total Training Length
max_frame_num: 12e8 # max frame 
eval_interval: 800 # evaluate the policy for every N training steps
save_interval: 800

# Training Environment
env:
  num_envs: 1024 # Number of drones for training
  max_episode_length: 1000
  env_spacing: 8.0 
  num_obstacles: 512
  map_range: [20.0, 20.0, 5.0] # [x, y, z], half extents
  platform_width: 2.0  # 原点周围保持平坦的区域宽度（正方形边长）
  enable_lidar: False

env_dyn:
  num_obstacles: 10 # set to zero if static env is needed
  vel_range: [0.5, 1.5]
  local_range: [5.0, 5.0, 5.0]

# If True, saves an additional global top-down view video during evaluation.
# The follow camera view video is always saved regardless of this setting.
global_view: False
viewer:
  eye: [-3., 0., 6.]
  lookat: [0., 0, 1.]
  resolution: [960, 720]

wandb:
  project: SRLC
  name: test_navRL
  entity: nickbit_ipec_group
  mode: offline 
  run_id: 
