defaults:
  - _self_
  - algo@_global_: ppo
  # Use direct path inclusion to allow multiple files from 'task' dir
  - /task/drone@_global_
  - /task/sim@_global_
  - /task/user_model@_global_
  - optional experiment: null
  - optional campaign: null

# Global Configurations
headless: True
device: "cuda:0"
seed: 42
log_output_dir: ${hydra:run.dir}
enable_yaw_control: false

# Training Length (can be overridden by experiment configs)
max_iterations: 1e6 # Total number of batches
eval_interval: 1000
save_interval: 1000

# Evaluation Settings
eval_visualization: true  
record_video: false
eval:
  checkpoint: null
  output_dir: ./eval_outputs
  seed: 42
  num_envs: 4
  record_video: true
  global_view: false
  keep_num_envs: false
  grid: null

# Hydra Configuration associated with this
hydra:
  output_subdir: null
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True

# wandb Configuration
wandb:
  project: SRLC
  name: srlc_default
  entity: nickbit_ipec_group
  mode: offline 
  run_id: 
